// The `mc` graph — Marcia Campbell, at her first oncology clinic visit. The
// workflow is the one handed over as-is; the voice, ears, inactivity, pre-fire,
// lip-sync and face are Jeremy's (jeremyCustoms), so the two rooms feel alike.

import type { AccentId } from '#/lib/accents'
import { md } from '../prompts/render'
import marciaPersona from '../prompts/roleplays/marcia/persona.md?raw'
import marciaFeedback from '../prompts/roleplays/marcia/feedback.md?raw'
import { JEREMY_FACES } from './jeremyCustoms'
import { buildVoiceCustoms, roleplayWebhook, sttForAccent } from './shared'

const MARCIA_PROMPT = md(marciaPersona)
const MARCIA_FEEDBACK_PROMPT = md(marciaFeedback)

const FEEDBACK_QUESTIONS =
  "1. Did the student introduce themselves and establish what the patient already understood before sharing results? 2. Did the student give a warning shot and deliver the CT results in clear, plain language? 3. Did the student accurately explain there was no visible spread to lymph nodes or liver, without overpromising? 4. Did the student explain the pancreatic cysts as a separate finding needing an MRCP, not as cancer spread? 5. Did the student take a focused symptom history (bleeding, swallowing, early satiety, weight loss, pain)? 6. Did the student explore family history for gastric or breast cancer and raise genetic counseling given her age and signet ring histology? 7. Did the student elicit the patient's concerns (prognosis, telling her children, work and income) and respond with empathy? 8. Did the student outline appropriate next staging steps (MRCP, endoscopic ultrasound, staging laparoscopy) and a multidisciplinary plan? 9. Did the student avoid or explain medical jargon? 10. Did the student check understanding and close with clear next steps and follow-up?"

export function buildMarciaCustoms(_userName: string, accent?: AccentId) {
  return {
    'warmup-agent': true,
    'process-type': 'stt-native',
    'lipsync-model': 'wav2lip',
    'lipsync-quality': 'low',
    faces: JEREMY_FACES,
    agent_id: {
      workflow: {
        variables: {
          user_input: { type: 'str' },
          llm_response: { type: 'str' },
          feedback: { type: 'str' },
          score: { type: 'float' },
          diagnosis_conversation_history: { type: 'list', default: [] },
          speak: { type: 'str' },
          node_type: { type: 'str' },
          feedback_questions: { type: 'str', value: FEEDBACK_QUESTIONS },
          end_diagnosis: { type: 'str' },
          movement: { type: 'list', default: [] },
        },
        start_node: 'greeting1',
        nodes: {
          greeting1: {
            type: 'out',
            parameters: {
              out_dict: {
                speak:
                  "Hi, doctor. I'm Marcia Campbell. Dr. Gupta sent me to see you about my scan results.",
              },
            },
            next: 'input1',
          },
          input1: {
            type: 'input',
            parameters: { input_variables: { user_input: 'str' } },
            next: ['llm', 'transcription1'],
          },
          transcription1: {
            type: 'out',
            parameters: { variables: ['user_input'] },
          },
          llm: {
            type: 'llm',
            parameters: {
              input_variables: {
                user_input: { type: 'str', description: 'The input text from the user.' },
              },
              prompt_template: 'base_llm',
              system_prompt: MARCIA_PROMPT,
              service: 'groq',
              model: 'openai/gpt-oss-120b',
              history_key: 'diagnosis_conversation_history',
              llm_return_type: {
                speak: {
                  type: 'str',
                  description: 'The response generated by the LLM based on the user input.',
                },
                movement: { type: 'list', description: 'For now keep it empty only' },
                end_diagnosis: {
                  type: 'str',
                  description: 'Indicates whether the diagnosis session should end.',
                },
              },
            },
            next: ['response1', 'judge_if_diagnosis_is_ended'],
          },
          response1: {
            type: 'out',
            parameters: { variables: ['speak', 'end_diagnosis', 'movement'] },
          },
          judge_if_diagnosis_is_ended: {
            type: 'conditional',
            parameters: {
              input_variables: { end_diagnosis: {} },
              mappings: { yes: 'feedback', no: 'input1' },
            },
          },
          feedback: {
            type: 'llm',
            parameters: {
              input_variables: {
                diagnosis_conversation_history: {
                  type: 'list',
                  description: 'the conversation hsitory of the diagnosis',
                },
                feedback_questions: { type: 'str', description: 'The feedback questions' },
              },
              prompt_template: 'base_llm',
              system_prompt: MARCIA_FEEDBACK_PROMPT,
              service: 'groq',
              model: 'openai/gpt-oss-120b',
              history_key: 'feedback_conversation_history',
              llm_return_type: {
                feedback: { type: 'str', description: 'The feedback text' },
                score: {
                  type: 'float',
                  description:
                    'The feedback score in float strictly between 0 and 1 after evaluation',
                },
              },
            },
            next: ['feedbacko'],
          },
          feedbacko: {
            type: 'out',
            parameters: { variables: ['feedback', 'score'] },
          },
        },
      },
      'webhook-url': roleplayWebhook(),
    },
    ...buildVoiceCustoms({
      accent,
      preFire: false,
      inactivityMessage: 'Hello? Are you still there?',
    }),
    tts_id: { service: 'deepgram', model: 'flux-naveen-en' },
    stt_id: sttForAccent(accent),
  }
}
